def menu():
    print( sep=' ')
    print('*' * 30)
    print('         BAR DO VKS!!')
    print('*' * 30)
    print( sep=' ')
    print('1 - Anotar Comanda')
    print('2 - Registrar Produto')
    print('3 - Consultar estoque')
    print('4 - Gerir Caixa')
    print('5 - Consultar saldo do caixa')
    print('6 - Sair')
    print( sep=' ')
    print('*' * 30)